Map<String, dynamic> items = {
  'item1': {
    'name': 'Apple',
    'image': 'assets/img/fruits/apple.png',
    'category': 'Fruits',
    'description': 'Apples are a popular fruit known for their crisp texture and sweet taste. They are high in fiber, vitamins, and antioxidants.',
    'price': 110,
    'rating': 4.0,
    'popularity': 100,
  },
  'item2': {
    'name': 'Carrot',
    'image': 'assets/img/veg/carrot.png',
    'category': 'Veggies',
    'description': 'Carrots are crunchy, nutritious vegetables rich in beta carotene, fiber, and vitamins, especially vitamin A.',
    'price': 38,
    'rating': 4.2,
    'popularity': 80,
  },
  'item3': {
    'name': 'Mango',
    'image': 'assets/img/fruits/mango.png',
    'category': 'Fruits',
    'description': 'Mangoes are tropical fruits with sweet, juicy flesh and are rich in vitamin C, A, and dietary fiber.',
    'price': 75,
    'rating': 4.0,
    'popularity': 90,
  },
  'item4': {
    'name': 'Pineapple',
    'image': 'assets/img/fruits/pineapple.png',
    'category': 'Fruits',
    'description': 'Pineapples are tropical fruits with tangy-sweet flavor, packed with vitamin C and enzymes that aid digestion.',
    'price': 52,
    'rating': 4.1,
    'popularity': 95,
  },
  'item5': {
    'name': 'Banana',
    'image': 'assets/img/fruits/banana.png',
    'category': 'Fruits',
    'description': 'Bananas are soft, sweet fruits known for their high potassium content and energy-boosting properties.',
    'price': 50,
    'rating': 4.5,
    'popularity': 85,
  },
  'item6': {
    'name': 'Strawberry',
    'image': 'assets/img/fruits/strawberry.png',
    'category': 'Fruits',
    'description': 'Strawberries are juicy berries packed with vitamin C, antioxidants, and a delicious sweet-tart flavor.',
    'price': 150,
    'rating': 4.3,
    'popularity': 70,
  },
  'item7': {
    'name': 'Watermelon',
    'image': 'assets/img/fruits/watermelon.png',
    'category': 'Fruits',
    'description': 'Watermelons are hydrating fruits with sweet, juicy red flesh, high in antioxidants and vitamins A and C.',
    'price': 32,
    'rating': 4.6,
    'popularity': 88,
  },
  'item8': {
    'name': 'Tomato',
    'image': 'assets/img/veg/tomato.png',
    'category': 'Veggies',
    'description': 'Tomatoes are versatile vegetables/fruits known for their rich flavor and high lycopene content, an antioxidant.',
    'price': 30,
    'rating': 4.5,
    'popularity': 92,
  },
  'item9': {
    'name': 'Orange',
    'image': 'assets/img/fruits/orange.png',
    'category': 'Fruits',
    'description': 'Oranges are citrus fruits rich in vitamin C, antioxidants, and fiber, promoting heart and immune health.',
    'price': 90,
    'rating': 4.4,
    'popularity': 75,
  },
  'item10': {
    'name': 'Onion',
    'image': 'assets/img/veg/onion.png',
    'category': 'Veggies',
    'description': 'Onions are pungent vegetables used in various cuisines, rich in antioxidants and compounds that promote heart health.',
    'price': 28,
    'rating': 4.1,
    'popularity': 65,
  },
  'item11': {
    'name': 'Walnuts',
    'image': 'assets/img/nuts.png',
    'category': 'Nuts',
    'description': 'Walnuts are nutrient-dense nuts high in omega-3 fatty acids, antioxidants, and brain-boosting properties.',
    'price': 75000,
    'rating': 1.0,
    'popularity': 89,
  },
  'item12': {
    'name': 'Veluthulli',
    'image': 'assets/img/veg/veluthulli.png',
    'category': 'Veggies',
    'description': 'Veluthulli, or garlic, is a pungent vegetable known for its medicinal properties and immune-boosting benefits.',
    'price': 52,
    'rating': 4.5,
    'popularity': 90,
  },
  'item13': {
    'name': 'Grapes',
    'image': 'assets/img/fruits/grapes.png',
    'category': 'Fruits',
    'description': 'Grapes are sweet, juicy berries rich in antioxidants and vitamins, promoting heart and skin health.',
    'price': 70,
    'rating': 4.6,
    'popularity': 78,
  },
  'item14': {
    'name': 'Cucumber',
    'image': 'assets/img/veg/tomato.png',
    'category': 'Veggies',
    'description': 'Cucumbers are refreshing vegetables high in water content and low in calories, perfect for hydration.',
    'price': 75000,
    'rating': 1.0,
    'popularity': 60,
  },
  'item15': {
    'name': 'Vendakka',
    'image': 'assets/img/veg/vendakka.png',
    'category': 'Veggies',
    'description': 'Vendakka, or okra, is a nutritious vegetable rich in fiber, vitamins, and antioxidants, ideal for digestion.',
    'price': 19,
    'rating': 4.8,
    'popularity': 85,
  },
  'item16': {
    'name': 'Chillies',
    'image': 'assets/img/veg/green-chilly.png',
    'category': 'Veggies',
    'description': 'Chillies are spicy vegetables that add heat to dishes and are high in capsaicin, known for its metabolism-boosting effects.',
    'price': 25,
    'rating': 4.6,
    'popularity': 87,
  },
  'item17': {
    'name': 'Peach',
    'image': 'assets/img/fruits/orange.png',
    'category': 'Fruits',
    'description': 'Peaches are juicy, sweet fruits rich in vitamins A, C, and fiber, perfect for refreshing snacks.',
    'price': 900000,
    'rating': 1.0,
    'popularity': 72,
  },
  'item18': {
    'name': 'Cabbage',
    'image': 'assets/img/veg/cabbage.png',
    'category': 'Veggies',
    'description': 'Cabbages are leafy vegetables rich in vitamins K, C, and antioxidants, known for their anti-inflammatory properties.',
    'price': 32,
    'rating': 4.2,
    'popularity': 68,
  },
  'item19': {
    'name': 'Potato',
    'image': 'assets/img/veg/potato.png',
    'category': 'Veggies',
    'description': 'Potatoes are starchy vegetables that are versatile in cooking and a good source of carbohydrates and potassium.',
    'price': 35,
    'rating': 4.0,
    'popularity': 82,
  },
  'item20': {
    'name': 'Lamb Chops',
    'image': 'assets/img/meat.png',
    'category': 'Meats',
    'description': 'Lamb chops are tender, flavorful cuts of meat, rich in protein, iron, and essential nutrients.',
    'price': 500,
    'rating': 1.0,
    'popularity': 91,
  },
};
